dbt_bq_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: positive-tuner-255507
      dataset: wallets_extraction
      threads: 4
      timeout_seconds: 300
      location: europe-central2
      keyfile: C:\Users\azdan\projects\dbt_bq\positive-tuner-255507-3f858f07cec5.json
