version: 2

sources:
  - name: solana_raw
    description: "Source for raw wallet and metadata extractions."
    database: positive-tuner-255507
    schema: wallets_extraction
    tables:
      - name: raw_solana_wallet_history
        description: "Raw snapshot of wallet asset holdings."
      - name: solana_mint_metadata
        description: "Raw mint metadata."
      - name: wallet_tokens
        description: "Raw wallet token holdings, test data."
      - name: tokens
        description: "Raw token metadata, test data."

  - name: solana_raw_prices
    description: "Source for token price data."
    database: positive-tuner-255507
    schema: bronze
    tables:
      - name: raw_solana_token_prices
        description: "Raw token price data, loaded daily."
      - name: raw_market_tokens_prices
        description: "Raw market token prices from CryptoDataDownload."
      - name: raw_wallet_history_features
        description: "Raw wallet history features, loaded daily."
      - name: raw_tokens_metadata
        description: "Raw token market metadata (price, liquidity, supplies, caps)."
      - name: raw_bitcoin_1min_prices
        description: "Raw Bitcoin 1-minute interval prices."

  - name: silver
    description: "Silver layer for cleaned and enriched data."
    database: positive-tuner-255507
    schema: silver
    tables:
      - name: fct_token_prices
        description: "Fact table of token prices with daily partitions."
      - name: fct__token_market_metadata
        description: "Fact table of token market metadata with daily partitions."
      - name: fct__bitcoin_hourly_prices
        description: "Fact table of Bitcoin hourly prices."
      - name: dim__token_score
        description: "Dimension table of token scores and labels."

  - name: gold
    description: "Gold layer for curated data."
    database: positive-tuner-255507
    schema: gold
    tables:
      - name: unique_tokens_base
        description: "Unique tokens held across all wallets."

  - name: raw
    description: "Source for raw Birdeye data."
    database: crypto-trading-474111
    schema: raw
    tables:
      - name: raw_birdeye_ohlcv
        description: "Raw snapshot of wallet asset holdings."
      - name: raw_birdeye_market_data
        description: "Raw Birdeye market data."
  - name: core
    description: "Source for core data."
    database: crypto-trading-474111
    schema: core
    tables:
      - name: token_metadata_jup_tmp
        description: "Token metadata from Jupiter API, temporary table."

  - name: eval
    description: "Evaluation database for ml model testing and validation."
    database: crypto-trading-474111
    schema: eval
    tables:
      - name: forest_72_gain20_loss25_og_duplicate_prod_results
  
  - name: streamed_datapublic
    description: "Silver layer for cleaned and enriched data, production."
    database: crypto-trading-474111
    schema: streamed_datapublic
    tables:
      - name: public_historical_prices
        description: "Fact table of token prices with daily partitions, production."